clc,clear;
jsontext = fileread('trackedDirectory.json');
directory = jsondecode(jsontext);
%[fileName, path] = uigetfile({'*.deva';'*.in'}, 'Select a file', directory);
fileName = '260963.deva';
path = 'E:\MGEATrials\Handstand_01_handstand\2\data\1020\';
path = [path, fileName];
if ~isfile(path)
    fprintf('Invalid path %s\n', path);
    return;
end
jsonText = fileread(path);
jsonStruct = jsondecode(jsonText);

columns = ["time", ...
    "pelvis_tx", "pelvis_ty", "pelvis_tz", ...
    "pelvis_tilt", "pelvis_list", "pelvis_rotation", ...
    "hip_flexion_r", "hip_adduction_r", "hip_rotation_r", "hip_flexion_l", "hip_adduction_l", "hip_rotation_l", ...
    "knee_angle_r", "ankle_angle_r", "knee_angle_l", "ankle_angle_l", ...
    "lumbar_extension", "lumbar_bending", "lumbar_rotation", ...
    "arm_flex_r", "arm_add_r", "arm_rot_r", "arm_flex_l", "arm_add_l", "arm_rot_l", ...
    "elbow_flex_r", "pro_sup_r", "elbow_flex_l", "pro_sup_l", ...
    "subtalar_angle_r", "mtp_angle_r", "subtalar_angle_l", "mtp_angle_l", ...
    "wrist_flex_r", "wrist_dev_r", "wrist_flex_l", "wrist_dev_l", ...
    "R.ASIS_tx", "R.ASIS_ty", "R.ASIS_tz", "L.ASIS_tx", "L.ASIS_ty", "L.ASIS_tz", ...
    "V.Sacral_tx", "V.Sacral_ty", "V.Sacral_tz", ...
    "R.Thigh.Upper_tx", "R.Thigh.Upper_ty", "R.Thigh.Upper_tz", ...
    "R.Thigh.Front_tx", "R.Thigh.Front_ty", "R.Thigh.Front_tz", ...
    "R.Thigh.Rear_tx", "R.Thigh.Rear_ty", "R.Thigh.Rear_tz", ...
    "L.Thigh.Upper_tx", "L.Thigh.Upper_ty", "L.Thigh.Upper_tz", ...
    "L.Thigh.Front_tx", "L.Thigh.Front_ty", "L.Thigh.Front_tz", ...
    "L.Thigh.Rear_tx", "L.Thigh.Rear_ty", "L.Thigh.Rear_tz", ...
    "R.Shank.Upper_tx", "R.Shank.Upper_ty", "R.Shank.Upper_tz", ...
    "R.Shank.Front_tx", "R.Shank.Front_ty", "R.Shank.Front_tz", ...
    "R.Shank.Rear_tx", "R.Shank.Rear_ty", "R.Shank.Rear_tz", ...
    "L.Shank.Upper_tx", "L.Shank.Upper_ty", "L.Shank.Upper_tz", ...
    "L.Shank.Front_tx", "L.Shank.Front_ty", "L.Shank.Front_tz", ...
    "L.Shank.Rear_tx", "L.Shank.Rear_ty", "L.Shank.Rear_tz", ...
    "R.Heel_tx", "R.Heel_ty", "R.Heel_tz", "L.Heel_tx", "L.Heel_ty", "L.Heel_tz", ...
    "R.Midfoot.Sup_tx", "R.Midfoot.Sup_ty", "R.Midfoot.Sup_tz", "R.Midfoot.Lat_tx", "R.Midfoot.Lat_ty", "R.Midfoot.Lat_tz", ...
    "R.Toe.Tip_tx", "R.Toe.Tip_ty", "R.Toe.Tip_tz", "L.Toe.Tip_tx", "L.Toe.Tip_ty", "L.Toe.Tip_tz", ...
    "L.Midfoot.Sup_tx", "L.Midfoot.Sup_ty", "L.Midfoot.Sup_tz", "L.Midfoot.Lat_tx", "L.Midfoot.Lat_ty", "L.Midfoot.Lat_tz", ...
    "Sternum_tx", "Sternum_ty", "Sternum_tz", ...
    "R.Acromium_tx", "R.Acromium_ty", "R.Acromium_tz", "L.Acromium_tx", "L.Acromium_ty", "L.Acromium_tz", ...
    "R.Bicep_tx", "R.Bicep_ty", "R.Bicep_tz", "L.Bicep_tx", "L.Bicep_ty", "L.Bicep_tz", ...
    "R.Elbow_tx", "R.Elbow_ty", "R.Elbow_tz", "L.Elbow_tx", "L.Elbow_ty", "L.Elbow_tz", ...
    "R.Wrist.Med_tx", "R.Wrist.Med_ty", "R.Wrist.Med_tz", "R.Wrist.Lat_tx", "R.Wrist.Lat_ty", "R.Wrist.Lat_tz", ...
    "L.Wrist.Med_tx", "L.Wrist.Med_ty", "L.Wrist.Med_tz", "L.Wrist.Lat_tx", "L.Wrist.Lat_ty", "L.Wrist.Lat_tz", ...
    "R.Toe.Lat_tx", "R.Toe.Lat_ty", "R.Toe.Lat_tz", "R.Toe.Med_tx", "R.Toe.Med_ty", "R.Toe.Med_tz", ...
    "L.Toe.Lat_tx", "L.Toe.Lat_ty", "L.Toe.Lat_tz", "L.Toe.Med_tx", "L.Toe.Med_ty", "L.Toe.Med_tz", ...
    "R.Temple_tx", "R.Temple_ty", "R.Temple_tz", "L.Temple_tx", "L.Temple_ty", "L.Temple_tz", ...
    "Top.Head_tx", "Top.Head_ty", "Top.Head_tz", ...
    ];
numData = length(jsonStruct.genotype.time);

fileID = fopen('osim.mot','w');
% fprintf(fileID, '%6s %12s\n', 'x', 'exp(x)');
fprintf(fileID, 'handtand_motion\n');
fprintf(fileID, 'nRows=256\n');
fprintf(fileID, 'nColumns=161\n\n');
fprintf(fileID, 'name handstand_motion\n');
fprintf(fileID, 'datacolumns 161\n');
fprintf(fileID, 'datarows 256\n');
fprintf(fileID, 'otherdata 1\n');
fprintf(fileID, 'range 0.000000 2.550000\n');
fprintf(fileID, 'endheader\n');

for colname = columns
    fprintf(fileID, '%s ', colname);
end
fprintf(fileID, '\n');
for rownumber = 1:numData
    for colname = columns
        if strcmp(colname, "time")
            fprintf(fileID, '%6f ', jsonStruct.genotype.time(rownumber));
        elseif strcmp(colname, "hip_flexion_r") || strcmp(colname, "hip_flexion_l")
            fprintf(fileID, '%6f ', -jsonStruct.phenotype.angles.hip(rownumber)*180/pi);
        elseif strcmp(colname, "wrist_flex_r") || strcmp(colname, "wrist_flex_l")
            fprintf(fileID, '%6f ', jsonStruct.phenotype.angles.wrist(rownumber)*180/pi+180);
        elseif strcmp(colname, "wrist_dev_r") || strcmp(colname, "wrist_dev_l")
            fprintf(fileID, '%6f ', 180);
        elseif strcmp(colname, "arm_flex_r") || strcmp(colname, "arm_flex_l")
            fprintf(fileID, '%6f ', jsonStruct.phenotype.angles.shoulder(rownumber)*180/pi+180);
        elseif strcmp(colname, "pelvis_tilt")
            fprintf(fileID, '%6f ', -jsonStruct.phenotype.angles.shoulder(rownumber)*180/pi+180);
        elseif strcmp(colname, "ankle_angle_r") || strcmp(colname, "ankle_angle_l")
            fprintf(fileID, '%6f ', -60);
        else
            fprintf(fileID, '0.000000 ');
        end
    end
    fprintf(fileID, '\n');
end

fclose(fileID);